### ISSUE TITLE
performance measure was failed when apply kotlin-dsl plugin.

### ISSUE THREAD

**Issue by ganadist** [Kotlin/k2-performance-metrics#11]
* `-Pkotlin.build.report.output=JSON,FILE` parameter was passed by https://github.com/Kotlin/k2-performance-metrics/blob/e19051848519c465fcb85bab68e1ca0a9a3061b5/buildSrc/src/main/kotlin/blogpost/Scenario.kt#L64 , but kotlin-dsl plugin (which is used by `buildSrc` or `build-logic`) don't accept this parameter.
* https://youtrack.jetbrains.com/issue/KT-66337
  * Json Report is supported since Kotlin 1.9.23, but Gradle 8.7 (or 8.0-rc-1) is still using kotlin 1.9.22

**Comment by Tapchicoma** [comment]
You should apply alongside `kotlin-dsl` plugin also "org.jetbrains.kotlin.jvm" plugin which version in controlled by `kotlin_version` property as it is written in README:
```
plugins {
     id("org.jetbrains.kotlin.jvm")
     `kotlin-dsl`
}
```
